name: Deploy DocC Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6

    - name: Build DocC Documentation
      run: |
          xcodebuild docbuild \
            -scheme Eginu \
            -destination "generic/platform=iOS" \
            -derivedDataPath DerivedData

          $(xcrun --find docc) process-archive \
             transform-for-static-hosting DerivedData/Build/Products/Debug-*/Eginu.doccarchive \
             --output-path ./docs \
             --hosting-base-path "SwiftEginu"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./docs
        
  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-slim
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}documentation/eginu/
      
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5
